# Generated by Django 4.0.1 on 2022-01-23 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='商品コード')),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='単価')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_datetime', models.DateTimeField(verbose_name='注文日時')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='販売単価')),
                ('count', models.IntegerField(verbose_name='個数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='calc.item', verbose_name='商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.order', verbose_name='注文')),
            ],
        ),
    ]
