# Generated by Django 4.0.1 on 2022-01-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='商品コード'),
        ),
    ]
